// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://localhost:7023/KisitliKisiBilgileri/Details/105
// Generated: 2026-06-09T17:09:06.654Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#2d3748' | '#ffffff' | '#212529' | '#000000' | '#1e293b' | '#34495e' | '#64748b' | '#6c757d' | '#0d6efd' | '#e2e8f0' | '#dc3545' | '#4f5d78' | '#0dcaf0' | '#198754' | '#ffc107' | '#21417a';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'Segoe UI';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700' | '300';

export type SpacingToken = '2px' | '12px' | '24px' | '28px' | '32px' | '40px' | '70px';

export type RadiusToken = '6px' | '10px' | '16px';

export type DurationToken = '150ms' | '200ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
